#!/bin/sh

#
# Copyright © 2015-2021 the original authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

##############################################################################
#  Gradle start up script for POSIX generated by Gradle.
##############################################################################

set -e

APP_NAME="Gradle"
APP_BASE_NAME=$(basename "$0")

MAX_FD="maximum"

warn () {
    echo "$*"
}

die () {
    echo
    echo "$*"
    echo
    exit 1
}

OS=$(uname)
case "$OS" in
  Darwin*)
    is_darwin=true
    ;;
  Linux*)
    is_linux=true
    ;;
  CYGWIN*|MINGW*|MSYS*)
    is_windows=true
    ;;
  *)
    ;;
esac

if [ -n "$JAVA_HOME" ] ; then
    if [ -x "$JAVA_HOME/jre/sh/java" ] ; then
        JAVACMD="$JAVA_HOME/jre/sh/java"
    else
        JAVACMD="$JAVA_HOME/bin/java"
    fi
    if [ ! -x "$JAVACMD" ] ; then
        die "ERROR: JAVA_HOME is set to an invalid directory: $JAVA_HOME

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."
    fi
else
    JAVACMD="java"
    if ! command -v java >/dev/null 2>&1 ; then
        die "ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH.

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."
    fi
fi

if [ -z "$GRADLE_USER_HOME" ] ; then
    GRADLE_USER_HOME="$HOME/.gradle"
fi

APP_HOME=$(cd "$(dirname "$0")" && pwd)

CLASSPATH="$APP_HOME/gradle/wrapper/gradle-wrapper.jar"

if [ "$is_darwin" = true ]; then
    if [ -n "$JAVA_OPTS" ]; then
        JAVA_OPTS="$JAVA_OPTS -Dfile.encoding=UTF-8"
    else
        JAVA_OPTS="-Dfile.encoding=UTF-8"
    fi
fi

if [ -n "$GRADLE_OPTS" ] ; then
    GRADLE_OPTS="$GRADLE_OPTS"
fi

if [ -n "$JAVA_OPTS" ] ; then
    DEFAULT_JVM_OPTS="$DEFAULT_JVM_OPTS"
fi

if [ -n "$GRADLE_OPTS" ] || [ -n "$JAVA_OPTS" ] || [ -n "$DEFAULT_JVM_OPTS" ] ; then
    JVM_OPTS="$DEFAULT_JVM_OPTS $JAVA_OPTS $GRADLE_OPTS"
else
    JVM_OPTS="-Xmx64m -Xms64m"
fi

if [ "$is_windows" = true ] ; then
    CLASSPATH=$(cygpath --path --mixed "$CLASSPATH")
    APP_HOME=$(cygpath --path --mixed "$APP_HOME")
fi

exec "$JAVACMD" $JVM_OPTS -classpath "$CLASSPATH" org.gradle.wrapper.GradleWrapperMain "$@"
